### ISSUE TITLE
only VIEW link appears in product add/edit unles capabilities are SAVED again

### ISSUE THREAD

**Issue by fervous** [wcvendors/wcvendors#322] opened 2016-10-04 04:03 UTC
https://www.wcvendors.com/help/topic/vendor-not-able-to-edit-their-products/

Perhaps after the latest update-- only the VIEW link was visible for the vendor to use when attempting to edit a product.  No edit, quick edit, or trash links.

During testing, I also experienced this.  I then went and checked WC Vendors capabilities (all were set correctly) and SAVED.

After saving, the links appeared again. (edit, quick edit, trash) and the issue was corrected.

**Comment by digitalchild** [comment] 2016-10-07 01:46
It's not a bug if you can fix it saving settings. Are you able to confirm this is a problem every time? I wasn't able to replicate on a fresh install.

**Comment by fervous** [comment] 2016-10-11 17:15
It is currently occurring on the dev site if logged in as a vendor.  It occurred on my own site after I updated free. I am not sure if it is happening every time, though.   
I have attached a screenshot of it on our wc vendors dev site.  I have not tired to fix it on the dev site by re-saving capabilities.  
![capabilities-not-saving-after-update](https://cloud.githubusercontent.com/assets/13291807/19280631/07749d66-8fa4-11e6-88b6-6197df268ff1.jpg)

**Comment by digitalchild** [comment] 2016-10-13 00:43
I just built a brand new install and can't replicate this issue. The only thing that has changed in the recent update was the ability for vendors to delete media. That is the only part that has changed possible capabilities.

**Comment by digitalchild** [comment] 2016-10-17 22:25
I am still unable to replicate this. I'm wondering if it has anything to do with the delete media capability we added. It shouldn't but I wouldn't be surprised.

**Comment by digitalchild** [comment] 2016-12-07 01:13
Is this still happening?

**Comment by digitalchild** [comment] 2017-01-16 23:52
Closing this as no further feedback.

**Closed by digitalchild** 2017-01-16 23:52 UTC
Labels: bug
