### ISSUE TITLE
"Change Primary Role as Vendor" Does not work

### ISSUE THREAD

**Issue by MarkKevin08** [wcvendors/wcvendors#671] opened 2020-07-30 10:08 UTC
**Describe the bug**
It seems that I was able to replicate this issue from my end while attempting to change the vendor role using the "Set vendor as primary role" command where it just reload the pending vendor page, no error can be seen in the front-end. Meanwhile, using the "Change role" command at this moment works without any issue -
https://share.getcloudapp.com/NQurEdol

**To Reproduce**
1. Register as a vendor
2. as an admin proceed to users >> pending vendors
3. use "Change Primary role to vendor command"

**Screenshots**
https://share.getcloudapp.com/NQurEdol

**Expected behavior**
User role should be changed to vendor

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WC Vendors and WooCommerce are active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by ketulsheth85** [comment] 2020-08-27 08:59
@MarkKevin08 
I'm not able to reproduce the issue.

Can you add more inputs or any specific step to generate this issue?

**Comment by mahlamusa** [comment] 2020-08-28 00:21
@ketulsheth85 @digitalchild Could this be that the code only allows default role to be set to Vendor only if the user is an approved Vendor?

I think this might be the be because the primary role should be set if the user already has that role, so, a pending_vendor is not a Vendor, so can not have a primary role as Vendor until first approve. If this is the case, then this is not a bug but how it should work.

- To change approve a vendor, the 'Change role to' should be used instead of 'Set default role to'

**Comment by digitalchild** [comment] 2020-08-28 04:20
Agreed, moving this to next release, not critical for 2.2.1

**Comment by digitalchild** [comment] 2020-11-06 08:16
This is working as intended.

**Closed by digitalchild** 2020-11-06 08:16 UTC
Labels: bug
